---
services:
  webtop:
    image: lscr.io/linuxserver/webtop:ubuntu-xfce
    container_name: 2026_FM_MoVe4BT
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=MoVe4BT #optional
    volumes:
      - ./data:/config
      # - /var/run/docker.sock:/var/run/docker.sock #optional (Linux only)
    ports:
      - 3000:3000
      - 3001:3001
    # devices:
    #   - /dev/dri:/dev/dri #optional (Linux only)
    shm_size: "1gb" #optional
    restart: unless-stopped
